# Generated by Django 4.0.3 on 2022-05-13 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='People',
            fields=[
                ('people_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('mobile_number', models.CharField(max_length=11)),
                ('phone_number', models.CharField(max_length=11)),
                ('note', models.TextField()),
            ],
        ),
    ]
